/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Favoriter, FavoriterInterface } from "../Favoriter";

const _abi = [
  {
    inputs: [],
    name: "favorite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasFavorited",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unfavorite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class Favoriter__factory {
  static readonly abi = _abi;
  static createInterface(): FavoriterInterface {
    return new utils.Interface(_abi) as FavoriterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Favoriter {
    return new Contract(address, _abi, signerOrProvider) as Favoriter;
  }
}
