/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { VisitorLog, VisitorLogInterface } from "../VisitorLog";

const _abi = [
  {
    inputs: [],
    name: "getVisitors",
    outputs: [
      {
        internalType: "address[]",
        name: "visitors",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "visitor",
        type: "address",
      },
    ],
    name: "hasVisited",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "logVisit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class VisitorLog__factory {
  static readonly abi = _abi;
  static createInterface(): VisitorLogInterface {
    return new utils.Interface(_abi) as VisitorLogInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VisitorLog {
    return new Contract(address, _abi, signerOrProvider) as VisitorLog;
  }
}
